### ISSUE TITLE
Use blake2-rfc crate

### ISSUE THREAD

**Issue by georgio** [SymbolicSoft/noiseexplorer#21]
It was recommended that we use https://docs.rs/blake2-rfc/0.2.18/blake2_rfc/ as it provides an implementation that better mirrors the BLAKE2 spec.

**Comment by burdges** [comment]
Also, I dislike the traits from the RustCrypto project myself, and avoid them whenever possible, but..

if you want a maintained blake2 with a digest trait then the [blake2 crate](https://docs.rs/blake2/0.8.0/blake2/) fits the bill.  A digest trait permits keeping the primitives abstracted in prims.rs but interacting with them directly in state.rs, if that separation matters.  It seemingly makes keying blake2 super painful, which is ridiculous and impact Noise.
