### ISSUE TITLE
pre-shared ephemeral key

### ISSUE THREAD

**Issue by tankf33der** [SymbolicSoft/noiseexplorer#22]
**FYI.** While testing [Monokex](https://github.com/LoupVaillant/Monokex) against explorer I've found patterns which passed on explorer, but failed in monokex.
```
Bad protocol: mike1: Pre-shared ephemeral key
mike1:
<- e
-> e
...
-> s, ee
<- se
```

**Comment by kaepora** [comment]
This is again a problem with Monokex. the Noise Protocol Framework spec [explicitly allows ephemeral keys in pre-messages](http://noiseprotocol.org/noise.html#handshake-pattern-basics).

**Comment by LoupVaillant** [comment]
Oh, I didn't know about stuff like XXfallback. Makes sense.

> This is again a problem with Monokex.

The "problem" is actually a deliberate choice. Monokex is meant to support only a small subset of what Noise is capable of. There won't be any protocol negotiation for instance.
