### ISSUE TITLE
Rust implementation's API is prone to nonce-reuse mistakes

### ISSUE THREAD

**Issue by mcginty** [SymbolicSoft/noiseexplorer#37]
In Noise Explorer's Rust implementation, `CipherState` (and therefore all the other states) should not implement `Clone` unless you either implement enforcement against catastrophic nonce reuse with `Arc<Atomic>` nonce types, or clearly warn users of the dangers involved, ideally made verbose into the API itself (i.e. naming the method which does the clone `dangerous_clone()`).

On that note, since not everyone may be aware, I suggest it would be good practice to add a warning in your README that this library is relatively new and for care to be taken by its consumers given its security-sensitive nature.

**Comment by georgio** [comment]
@mcginty thank you for pointing this out. I will deal with this right away.
Ideally, a `NoiseSession` should not be cloned.

**Comment by mcginty** [comment]
@georgio no problem at all.

I just want to state again though that I think not putting a disclaimer about the immaturity of the library while actively marketing it to companies to use in their applications feels reckless to me.

**Comment by kaepora** [comment]
@mcginty Hi Jake,

We're fairly confident with the current status of the Noise Explorer Rust/Go code and think that it's currently ready for use in production.

All generated implementations come with their own [`rustdoc`-formatted documentation](https://github.com/SymbolicSoft/noiseexplorer#implementation-documentation) for their API, containing information on how to correctly use the API in practice. Indeed, leaving `Clone` in there implemented for `CipherState` was unnecessary, and I'm glad that this is now addressed. However, I don't think that this unnecessary state property constitutes an abject reflection on the security of the rest of the code, if the API is used correctly.

We will continue to strive to make the API more difficult to misuse going forward.

**Comment by mcginty** [comment]
@kaepora unfortunately the documentation didn't say "don't use this method that's implemented on this struct because it will lead to nonce reuse."

I'm not saying that this issue is a massive one, but I *am* saying that eventually, someone somewhere would inevitably have cloned a session to appease the borrow checker, leading to a very bad time for them. Which, I believe, makes this more serious than `Clone` simply being "unnecessary".

As for your confidence level on the production-worthiness of the library, I don't know what review (internal or external) you've done, but these types of leftovers are often seen as "code smell" which is why I chose to leave that opinion here. I'm advocating for conservative and cautious claims about the maturity of security software in general, which I believe improves trust in the ecosystem on the whole.

**Comment by kaepora** [comment]
> @kaepora unfortunately the documentation didn't say "don't use this method that's implemented on this struct because it will lead to nonce reuse."

It's silly to expect such a warning to exist in the documentation. There's an infinite number of ways in which a user can misuse an API, and we can't predict every single one. What we _can_ do is make use of Rust's type features to restrict that spectrum as much as possible, and that's a good thing, too, because other languages such as Golang don't even allow us that luxury -- there's nothing we can do to completely prevent a determined user from cloning their state in their Golang implementation, for example, or in most other programming languages.

A library being deemed production-ready doesn't mean that it's deemed perfect. We expect our code to continuously improve and tighten, and so we welcome future input and insight.
